
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
      working-directory:  ./dist/browser
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      working-directory: ./dist/browser
      with:
        server: ftp.hd724.com
        username: mhmdhose
        password: ${{ secrets.ftp_password }}
        server-dir: /public_html/
